// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01___Explicacao.Context;

#nullable disable

namespace _01___Explicacao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423094051_SeedClientesEEnderecos")]
    partial class SeedClientesEEnderecos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("_01___Explicacao.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mariana Souza",
                            Telefone = "(11) 90000-0000"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Carlos Henrique Lima",
                            Telefone = "(21) 99876-1234"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Fernanda Alves",
                            Telefone = "(31) 99123-4567"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Rafael Costa",
                            Telefone = "(41) 98888-7777"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Juliana Martins",
                            Telefone = "(51) 99777-6666"
                        });
                });

            modelBuilder.Entity("_01___Explicacao.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Enderecos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Centro",
                            Cep = "01000-000",
                            Cidade = "Sao Paulo",
                            ClienteId = 1,
                            Complemento = "Apto 12",
                            Estado = "SP",
                            Logradouro = "Rua das Flores",
                            Numero = "120"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Copacabana",
                            Cep = "22010-000",
                            Cidade = "Rio de Janeiro",
                            ClienteId = 2,
                            Estado = "RJ",
                            Logradouro = "Avenida Atlantica",
                            Numero = "450"
                        },
                        new
                        {
                            Id = 3,
                            Bairro = "Funcionarios",
                            Cep = "30160-011",
                            Cidade = "Belo Horizonte",
                            ClienteId = 3,
                            Complemento = "Sala 5",
                            Estado = "MG",
                            Logradouro = "Rua da Bahia",
                            Numero = "980"
                        },
                        new
                        {
                            Id = 4,
                            Bairro = "Centro",
                            Cep = "80020-310",
                            Cidade = "Curitiba",
                            ClienteId = 4,
                            Estado = "PR",
                            Logradouro = "Rua XV de Novembro",
                            Numero = "300"
                        },
                        new
                        {
                            Id = 5,
                            Bairro = "Partenon",
                            Cep = "90610-001",
                            Cidade = "Porto Alegre",
                            ClienteId = 5,
                            Complemento = "Bloco B",
                            Estado = "RS",
                            Logradouro = "Avenida Ipiranga",
                            Numero = "1500"
                        });
                });

            modelBuilder.Entity("_01___Explicacao.Models.Endereco", b =>
                {
                    b.HasOne("_01___Explicacao.Models.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("_01___Explicacao.Models.Endereco", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("_01___Explicacao.Models.Cliente", b =>
                {
                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
