// <auto-generated />
using System;
using EcommerceCleanArchitecture.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceCleanArchitecture.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508101356_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcommerceCleanArchitecture.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "12345678901",
                            Email = "ana@ecommerce.local",
                            Nome = "Ana Souza",
                            Telefone = "11999990001"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "12345678902",
                            Email = "bruno@ecommerce.local",
                            Nome = "Bruno Lima",
                            Telefone = "11999990002"
                        });
                });

            modelBuilder.Entity("EcommerceCleanArchitecture.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            CriadoEm = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Observacao = "Entregar em horario comercial."
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            CriadoEm = new DateTime(2026, 5, 8, 0, 30, 0, 0, DateTimeKind.Utc),
                            Observacao = "Cliente solicitou embalagem para presente."
                        });
                });

            modelBuilder.Entity("EcommerceCleanArchitecture.Domain.Entities.PedidoProduto", b =>
                {
                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("PedidoId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PedidoProdutos");

                    b.HasData(
                        new
                        {
                            PedidoId = 1,
                            ProdutoId = 1,
                            PrecoUnitario = 5499.90m,
                            Quantidade = 1
                        },
                        new
                        {
                            PedidoId = 1,
                            ProdutoId = 2,
                            PrecoUnitario = 129.90m,
                            Quantidade = 2
                        },
                        new
                        {
                            PedidoId = 2,
                            ProdutoId = 3,
                            PrecoUnitario = 349.90m,
                            Quantidade = 1
                        });
                });

            modelBuilder.Entity("EcommerceCleanArchitecture.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Notebook para trabalho e estudo.",
                            Nome = "Notebook Pro 14",
                            Preco = 5499.90m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Mouse ergonomico com conexao sem fio.",
                            Nome = "Mouse Sem Fio",
                            Preco = 129.90m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Teclado mecanico com iluminacao RGB.",
                            Nome = "Teclado Mecanico",
                            Preco = 349.90m
                        });
                });

            modelBuilder.Entity("EcommerceCleanArchitecture.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("EcommerceCleanArchitecture.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EcommerceCleanArchitecture.Domain.Entities.PedidoProduto", b =>
                {
                    b.HasOne("EcommerceCleanArchitecture.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceCleanArchitecture.Domain.Entities.Produto", "Produto")
                        .WithMany("Pedidos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EcommerceCleanArchitecture.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("EcommerceCleanArchitecture.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("EcommerceCleanArchitecture.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
